contribution/urls.py
from django.urls import path
from .views import (
    ContributionCategoryCreateView,
    ContributionCategoryUpdateView,
    ContributionCategoryDeleteView,
    ContributionUploadView,
    ContributionListView,
    ContributionDetailView,
    SelectedContributionListView,
    mark_as_selected,
    mark_as_unselected,
    contribution_delete,
    comment_create,
    CommentListView
)

urlpatterns = [
    # Contribution Category
    path('category/create/', ContributionCategoryCreateView.as_view(),
         name='category_create'),
    path('category/<slug>/update/', ContributionCategoryUpdateView.as_view(),
         name='category_update'),
    path('category/<slug>/delete/', ContributionCategoryDeleteView.as_view(),
         name='category_delete'),
    # Contribution
    path('upload/', ContributionUploadView.as_view(), name='upload'),
    path('delete/', contribution_delete, name='contribution_delete'),
    path('<slug>/detail/', ContributionDetailView.as_view(), name='contribution_detail'),
    path('list/', ContributionListView.as_view(), name='contribution_list'),
    path('selected/list/', SelectedContributionListView.as_view(), name='selected_contribution_list'),
    path('<slug>/mark/selected/', mark_as_selected, name='contribution_selected'),
    path('<slug>/mark/unselected/', mark_as_unselected, name='contribution_unselected'),
    #comment
    path('comment/<slug>/create/', comment_create, name='comment_create'),
    path('comment/<slug>/view/', CommentListView.as_view(), name='comment_view'),
]

magfetch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView, statistics_search
from .routers import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('account/', include('accounts.urls')),
    path('system/data/', include(('system_data.urls', 'system_data'), namespace='system_data')),
    path('utils/', include(('utils.urls', 'utils'), namespace='utils')),
    path('contribution/', include(('contribution.urls', 'contribution'), namespace='contribution')),
    path('api/', include(router.urls)),
    path('statistics/search/', statistics_search, name='statistics_search')
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

utils/urls.py
from django.urls import path
from .views import AnnouncementDetailView, NotificationDetailView, NotificationListView, mark_all_as_read

urlpatterns = [
    path('announcement/<slug>/detail/', AnnouncementDetailView.as_view(), name='announcement_detail'),
    path('notification/list/', NotificationListView.as_view(), name='notification_list'),
    path('notification/<slug>/detail/', NotificationDetailView.as_view(), name='notification_detail'),
    path('notification/all/read/', mark_all_as_read, name='mark_all_as_read')
]

contribution/views.py
from django.shortcuts import render, redirect, get_object_or_404
# Models Import
from .models import ContributionCategory, Contribution, Comment
from accounts.models import UserProfile
from system_data.models import Date
from suspicious.models import Suspicious
# Form import
from .forms import (
    ContributionCategoryCreateForm,
    ContributionUploadForm,
)
# generic view import
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
# other import
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse
from django.core.paginator import Paginator
from django import forms
from django.contrib import messages
import datetime
from .handlers import create_notification_to_mc_upload
from django.core.mail import EmailMultiAlternatives
from django.core.files.storage import default_storage
import os
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse 
from accounts.utils import get_client_ip
from uuid import getnode as get_mac



# Contribution Category Create View
@method_decorator(login_required, name='dispatch')
class ContributionCategoryCreateView(CreateView):
    template_name = 'category/create.html'
    form_class = ContributionCategoryCreateForm

    def form_valid(self, form):
        title = form.instance.title
        category_for = form.instance.category_for
        # category_for = form.instance.category_for
        qs = ContributionCategory.objects.filter(
            title__iexact=title, category_for=category_for)
        if qs.exists():
            form.add_error(
                'title', forms.ValidationError(
                    "This Category is alreay exists! Please try another one."
                )
            )
            return super().form_invalid(form)
        else:
            messages.add_message(self.request, messages.SUCCESS,
                                 "Category has been added successfully!")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('contribution:category_create')

    def get_context_data(self, **kwargs):
        context = super(ContributionCategoryCreateView,
                        self).get_context_data(**kwargs)
        doc_category = ContributionCategory.objects.filter(
            category_for=0).order_by('-created_at')
        img_category = ContributionCategory.objects.filter(
            category_for=1).order_by('-created_at')
        context['doc_categories'] = doc_category
        context['doc_categories_count'] = doc_category.count()
        context['img_categories'] = img_category
        context['img_categories_count'] = img_category.count()
        return context

    def user_passes_test(self, request):
        user = request.user
        if UserProfile.objects.filter(user=user).first().role == 1:
            return True
        return False

    def dispatch(self, request, *args, **kwargs):
        instance_user = self.request.user
        if not self.user_passes_test(request):
            suspicious_user = Suspicious.objects.filter(user=instance_user)
            if suspicious_user.exists():
                suspicious_user_instance = Suspicious.objects.get(
                    user=instance_user)
                current_attempt = suspicious_user_instance.attempt
                total_attempt = current_attempt + 1
                update_time = datetime.datetime.now()
                suspicious_user.update(
                    attempt=total_attempt, last_attempt=update_time)
            else:
                client_ip = get_client_ip(request)
                client_mac = get_mac()
                Suspicious.objects.get_or_create(user=instance_user, ip=client_ip, mac=client_mac)
            messages.add_message(self.request, messages.ERROR,
                                 "You are not allowed. Your account is being tracked for suspicious activity !"
                                 )
            return HttpResponseRedirect(reverse('home'))
        return super(ContributionCategoryCreateView, self).dispatch(request, *args, **kwargs)


# Contribution Category Update View
@method_decorator(login_required, name='dispatch')
class ContributionCategoryUpdateView(UpdateView):
    template_name = 'category/update.html'
    form_class = ContributionCategoryCreateForm

    def get_object(self):
        slug = self.kwargs['slug']
        qs = ContributionCategory.objects.filter(slug=slug)
        if qs.exists():
            return qs.first()
        return None

    def form_valid(self, form):
        pre = self.get_object()
        title = form.instance.title
        category_for = form.instance.category_for
        if not pre.title == title:
            qs = ContributionCategory.objects.filter(
                title__iexact=title, category_for=category_for)
            if qs.exists():
                form.add_error(
                    'title', forms.ValidationError(
                        "This Category is alreay exists! Please try another one."
                    )
                )
                return super().form_invalid(form)
        messages.add_message(self.request, messages.SUCCESS,
                             "Category has been added successfully!")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('contribution:category_create')

    def get_context_data(self, **kwargs):
        context = super(ContributionCategoryUpdateView,
                        self).get_context_data(**kwargs)
        doc_category = ContributionCategory.objects.filter(
            category_for=0).order_by('-created_at')
        img_category = ContributionCategory.objects.filter(
            category_for=1).order_by('-created_at')
        context['doc_categories'] = doc_category
        context['doc_categories_count'] = doc_category.count()
        context['img_categories'] = img_category
        context['img_categories_count'] = img_category.count()
        return context

    def user_passes_test(self, request):
        user = request.user
        if UserProfile.objects.filter(user=user).first().role == 1:
            return True
        return False

    def dispatch(self, request, *args, **kwargs):
        instance_user = self.request.user
        if not self.user_passes_test(request):
            suspicious_user = Suspicious.objects.filter(user=instance_user)
            if suspicious_user.exists():
                suspicious_user_instance = Suspicious.objects.get(
                    user=instance_user)
                current_attempt = suspicious_user_instance.attempt
                total_attempt = current_attempt + 1
                update_time = datetime.datetime.now()
                suspicious_user.update(
                    attempt=total_attempt, last_attempt=update_time)
            else:
                client_ip = get_client_ip(request)
                client_mac = get_mac()
                Suspicious.objects.get_or_create(user=instance_user, ip=client_ip, mac=client_mac)
            messages.add_message(self.request, messages.ERROR,
                                 "You are not allowed. Your account is being tracked for suspicious activity !"
                                 )
            return HttpResponseRedirect(reverse('home'))
        return super(ContributionCategoryUpdateView, self).dispatch(request, *args, **kwargs)


# Contribution Category Delete View
@method_decorator(login_required, name='dispatch')
class ContributionCategoryDeleteView(DeleteView):
    template_name = 'category/delete.html'
    form_class = ContributionCategoryCreateForm

    def get_object(self):
        slug = self.kwargs['slug']
        qs = ContributionCategory.objects.filter(slug=slug)
        if qs.exists():
            return qs.first()
        return None

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS,
                             "Category has been deleted successfully!")
        return reverse('contribution:category_create')

    def get_context_data(self, **kwargs):
        context = super(ContributionCategoryDeleteView,
                        self).get_context_data(**kwargs)
        doc_category = ContributionCategory.objects.filter(
            category_for=0).order_by('-created_at')
        img_category = ContributionCategory.objects.filter(
            category_for=1).order_by('-created_at')
        context['doc_categories'] = doc_category
        context['doc_categories_count'] = doc_category.count()
        context['img_categories'] = img_category
        context['img_categories_count'] = img_category.count()
        return context

    def user_passes_test(self, request):
        user = request.user
        if UserProfile.objects.filter(user=user).first().role == 1:
            return True
        return False

    def dispatch(self, request, *args, **kwargs):
        instance_user = self.request.user
        if not self.user_passes_test(request):
            suspicious_user = Suspicious.objects.filter(user=instance_user)
            if suspicious_user.exists():
                suspicious_user_instance = Suspicious.objects.get(
                    user=instance_user)
                current_attempt = suspicious_user_instance.attempt
                total_attempt = current_attempt + 1
                update_time = datetime.datetime.now()
                suspicious_user.update(
                    attempt=total_attempt, last_attempt=update_time)
            else:
                client_ip = get_client_ip(request)
                client_mac = get_mac()
                Suspicious.objects.get_or_create(user=instance_user, ip=client_ip, mac=client_mac)
            messages.add_message(self.request, messages.ERROR,
                                 "You are not allowed. Your account is being tracked for suspicious activity !"

contribution/templates/category/create.html
{% extends 'base.html' %}

{% block head_title %}{% block page_title %}{% block breadcrumb %}
Contribution Category
{% endblock %}{% endblock %}{% endblock %}

{% block content %}

<div class="row">
    <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
        <section class="panel panel-default">
            <header class="panel-heading font-bold text-center">Create Contribution Category</header>
            <div class="panel-body">
                <form class="form" method="POST">
                    {% csrf_token %}
                    {% include 'snippets/form.html' %}
                    <button type="submit" class="btn btn-sm btn-primary pull-left">Create</button>
                </form>
            </div>
        </section>
    </div>
    {% if doc_categories_count >= 1 %}
    <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
        {% include 'category/doc-cat-list.html' %}
    </div>
    {% endif %}
    {% if img_categories_count >= 1 %}
    <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
        {% include 'category/img-cat-list.html' %}
    </div>
    {% endif %}
</div>


{% endblock %}

contribution/templates/category/delete.html
{% extends 'base.html' %}

{% block head_title %}{% block page_title %}{% block breadcrumb %}
Delete Category
{% endblock %}{% endblock %}{% endblock %}

{% block content %}

<div class="row">
    <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
        <section class="panel panel-default">
            <header class="panel-heading font-bold text-center">
                Delete Category
                <strong class="text-lg c-text-info">
                    <i>{{object}}</i>
                </strong>
            </header>
            <div class="panel-body">
                <form class="form" method="POST">
                    <fieldset class="m-md">
                        <p class="text-danger text-center font-bold font-15">
                            Are you sure you want to delete Category
                            <strong class="text-lg c-text-info">
                                <i>{{object}}</i>
                            </strong> ?
                        </p>
                    </fieldset>
                    {% csrf_token %}
                    {% include 'snippets/form.html' %}
                    <button type="submit" class="btn btn-sm btn-primary pull-left">Confirm & Delete</button>
                </form>
                <a href="{% url 'contribution:category_create' %}" class="btn btn-xs btn-danger pull-right">
                    <i class="fa fa-mail-reply"></i> Cancel
                </a>
            </div>
        </section>
    </div>
    {% if doc_categories_count >= 1 %}
    <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
        {% include 'category/doc-cat-list.html' %}
    </div>
    {% endif %}
    {% if img_categories_count >= 1 %}
    <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
        {% include 'category/img-cat-list.html' %}
    </div>
    {% endif %}
</div>

{% endblock %}

contribution/templates/category/doc-cat-list.html
{% if doc_categories_count >= 1 %}

<section class="panel panel-default">
  <header class="panel-heading font-bold text-center">
    Document Category List
    <span class="label bg-dark c-text-info">{{ doc_categories_count }}</span>
  </header>
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-striped b-t b-light">
        <thead>
          <tr>
            <th>Title</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for category in doc_categories %}
          <tr>
            <td class="c-text-dark">
              {{ category.title }}
            </td>
            <td>
              <a href="{% url 'contribution:category_update' slug=category.slug %}">
                <i class="fa fa-edit text-info"></i> Edit
              </a>
              <a href="{% url 'contribution:category_delete' slug=category.slug %}">
                <i class="fa fa-trash-o text-danger m-l-sm"></i> Delete
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

</section>

{% else %}
<p class="text-center c-text-warning">
  There's no Document Category yet!
</p>

{% endif %}

contribution/templates/category/img-cat-list.html
{% if img_categories_count >= 1 %}

<section class="panel panel-default">
    <header class="panel-heading font-bold text-center">
        Image Category List
        <span class="label bg-dark c-text-info">{{ img_categories_count }}</span>
    </header>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped b-t b-light">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for category in img_categories %}
                    <tr>
                        <td class="c-text-dark">
                            {{ category.title }}
                        </td>
                        <td>
                            <a href="{% url 'contribution:category_update' slug=category.slug %}">
                                <i class="fa fa-edit text-info"></i> Edit
                            </a>
                            <a href="{% url 'contribution:category_delete' slug=category.slug %}">
                                <i class="fa fa-trash-o text-danger m-l-sm"></i> Delete
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</section>

{% else %}
<p class="text-center c-text-warning">
    There's no Image Category yet!
</p>

{% endif %}

contribution/templates/category/update.html
{% extends 'base.html' %}

{% block head_title %}{% block page_title %}{% block breadcrumb %}
Update Category
{% endblock %}{% endblock %}{% endblock %}

{% block content %}

<div class="row">
    <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
        <section class="panel panel-default">
            <header class="panel-heading font-bold text-center">
                Update Category
                <strong class="text-lg c-text-info">
                    <i>{{object}}</i>
                </strong>
            </header>
            <div class="panel-body">
                <form class="form" method="POST">
                    {% csrf_token %}
                    {% include 'snippets/form.html' %}
                    <button type="submit" class="btn btn-sm btn-primary pull-left">Update</button>
                </form>
                <a href="{% url 'contribution:category_create' %}" class="btn btn-xs btn-danger pull-right">
                    <i class="fa fa-mail-reply"></i> Cancel
                </a>
            </div>
        </section>
    </div>
    {% if doc_categories_count >= 1 %}
    <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
        {% include 'category/doc-cat-list.html' %}
    </div>
    {% endif %}
    {% if img_categories_count >= 1 %}
    <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
        {% include 'category/img-cat-list.html' %}
    </div>
    {% endif %}
</div>

{% endblock %}