contribution/urls.py
from django.urls import path
from .views import (
    ContributionCategoryCreateView,
    ContributionCategoryUpdateView,
    ContributionCategoryDeleteView,
    ContributionUploadView,
    ContributionListView,
    ContributionDetailView,
    SelectedContributionListView,
    mark_as_selected,
    mark_as_unselected,
    contribution_delete,
    comment_create,
    CommentListView
)

urlpatterns = [
    # Contribution Category
    path('category/create/', ContributionCategoryCreateView.as_view(),
         name='category_create'),
    path('category/<slug>/update/', ContributionCategoryUpdateView.as_view(),
         name='category_update'),
    path('category/<slug>/delete/', ContributionCategoryDeleteView.as_view(),
         name='category_delete'),
    # Contribution
    path('upload/', ContributionUploadView.as_view(), name='upload'),
    path('delete/', contribution_delete, name='contribution_delete'),
    path('<slug>/detail/', ContributionDetailView.as_view(), name='contribution_detail'),
    path('list/', ContributionListView.as_view(), name='contribution_list'),
    path('selected/list/', SelectedContributionListView.as_view(), name='selected_contribution_list'),
    path('<slug>/mark/selected/', mark_as_selected, name='contribution_selected'),
    path('<slug>/mark/unselected/', mark_as_unselected, name='contribution_unselected'),
    #comment
    path('comment/<slug>/create/', comment_create, name='comment_create'),
    path('comment/<slug>/view/', CommentListView.as_view(), name='comment_view'),
]

magfetch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView, statistics_search
from .routers import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('account/', include('accounts.urls')),
    path('system/data/', include(('system_data.urls', 'system_data'), namespace='system_data')),
    path('utils/', include(('utils.urls', 'utils'), namespace='utils')),
    path('contribution/', include(('contribution.urls', 'contribution'), namespace='contribution')),
    path('api/', include(router.urls)),
    path('statistics/search/', statistics_search, name='statistics_search')
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

system_data/urls.py
from django.urls import path
from .views import DateCreateView, DateUpdateView

urlpatterns = [
    path('schedule/create/', DateCreateView.as_view(), name='date_create'),
    path('schedule/update/', DateUpdateView.as_view(), name='date_update'),
]

utils/urls.py
from django.urls import path
from .views import AnnouncementDetailView, NotificationDetailView, NotificationListView, mark_all_as_read

urlpatterns = [
    path('announcement/<slug>/detail/', AnnouncementDetailView.as_view(), name='announcement_detail'),
    path('notification/list/', NotificationListView.as_view(), name='notification_list'),
    path('notification/<slug>/detail/', NotificationDetailView.as_view(), name='notification_detail'),
    path('notification/all/read/', mark_all_as_read, name='mark_all_as_read')
]

magfetch/views.py
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import render
from accounts.models import UserProfile
from contribution.models import Contribution, Comment
from django.db.models import Q
from django.contrib import messages
import datetime
import re

# @method_decorator(login_required, name='dispatch')
# class HomeView(TemplateView):
#     template_name = 'pages/home.html'


@method_decorator(login_required, name='dispatch')
class HomeView(TemplateView):
    def get(self, request, *args, **kwargs):
        user = request.user
        today = datetime.datetime.now()
        user_profile_filter = UserProfile.objects.filter(user=user)
        if user_profile_filter.exists():
            profile = user_profile_filter.first()
            # -------- Administrative Dashboard View -----------
            if profile.role == 0 or profile.role == 1 or profile.role == 2 or profile.role == 3:
                contributions = Contribution.objects.all().latest()
                contributors = UserProfile.objects.filter(~Q(user_contribution=None)).exclude(~Q(user_contribution__created_at__year=today.year))
                context = {
                    'contributions': contributions,
                    'contributions_this_year': contributions.contributions_this_year(),
                    'contributions_selected': contributions.selected().contributions_by_faculty(request.user.profile).contributions_this_year(),
                    'uncommented_contributions': contributions.uncommented().contributions_by_faculty(request.user.profile).contributions_this_year(),
                    'contributions_doc': contributions.contributions_doc().contributions_by_faculty(request.user.profile).contributions_this_year(),
                    'contributions_img': contributions.contributions_img().contributions_by_faculty(request.user.profile).contributions_this_year(),
                    'special_comments': contributions.filter(user_contribution_file__is_special=True).contributions_this_year(),
                    # All Contributions By Faculty
                    'IT_contributions_all': contributions.filter(user__faculty__code__iexact='IT'),
                    'CSE_contributions_all': contributions.filter(user__faculty__code__iexact='CSE'),
                    'SWE_contributions_all': contributions.filter(user__faculty__code__iexact='SWE'),
                    'EEE_contributions_all': contributions.filter(user__faculty__code__iexact='EEE'),
                    # All Contributions By Faculty within each year
                    'IT_contributions': contributions.filter(user__faculty__code__iexact='IT').contributions_this_year(),
                    'CSE_contributions': contributions.filter(user__faculty__code__iexact='CSE').contributions_this_year(),
                    'SWE_contributions': contributions.filter(user__faculty__code__iexact='SWE').contributions_this_year(),
                    'EEE_contributions': contributions.filter(user__faculty__code__iexact='EEE').contributions_this_year(),
                    # All Contributors By Faculty within each year
                    'IT_contributors': contributors.filter(faculty__code__iexact='IT'),
                    'CSE_contributors': contributors.filter(faculty__code__iexact='CSE'),
                    'SWE_contributors': contributors.filter(faculty__code__iexact='SWE'),
                    'EEE_contributors': contributors.filter(faculty__code__iexact='EEE'),
                    # MM Report
                    'contributions_selected_mm': contributions.selected().contributions_this_year(),
                    'uncommented_contributions_mm': contributions.uncommented().contributions_this_year(),
                    'special_comments_mm': contributions.filter(user_contribution_file__is_special=True).contributions_by_year(today.year),
                    'contributions_doc_mm': contributions.contributions_doc().contributions_this_year(),
                    'contributions_img_mm': contributions.contributions_img().contributions_this_year(),
                    # Extra
                    'input_value':today.year,
                    'contributions_by_year': contributions.contributions_by_year(today.year),
                    'contributions_by_year_faculty': contributions.contributions_by_year(today.year).contributions_by_faculty(request.user.profile),
                    'contributors_by_year': contributors
                }
                return render(request, "pages/home.html", context=context)
            # ------- Student Landing Page View -------
            if profile.role == 4:
                # If submited check
                submitted_filter = Contribution.objects.filter(
                    user=profile, updated_at__year=today.year)
                if submitted_filter.exists():
                    is_submitted = True
                else:
                    is_submitted = False
                context = {
                    'is_submitted': is_submitted,
                    'contributions': submitted_filter
                }
                return render(request, "landing/pages/home.html", context=context)
            # ------- Django Admin View -------
            if profile.user.is_staff == True:
                return render(request, "pages/home.html")
            # ------- Anonymous View -------
            if profile.role == 7:
                return render(request, "anonymous.html")
        return render(request, "anonymous.html")


def statistics_search(request):
    user = request.user
    user_profile_filter = UserProfile.objects.filter(user=user)
    today = datetime.datetime.now()
    if user_profile_filter.exists():
        profile = user_profile_filter.first()
        # -------- Administrative Dashboard View -----------
        if profile.role == 0 or profile.role == 1 or profile.role == 2 or profile.role == 3:
            request_year = today.year
            if request.method == 'POST':
                request_year = request.POST.get('contribution_search')
                if not request_year == None:
                    allowed_chars = re.match(r'^[0-9]+$', request_year)
                    length = len(request_year)
                    if not allowed_chars or length >= 5:
                        messages.add_message(request, messages.WARNING,
                             "Please enter valid year!!!")
                        context = {
                            'error': True,
                            'input_value':today.year
                        }
                        return render(request, "pages/home.html", context=context)
                    else:
                        contributions = Contribution.objects.all().latest()
                        contributors = UserProfile.objects.filter(~Q(user_contribution=None)).exclude(~Q(user_contribution__created_at__year=request_year))
                        context = {
                            'contributions': contributions,
                            'contributions_this_year': contributions.contributions_this_year(),
                            'contributions_selected': contributions.selected().contributions_by_faculty(request.user.profile).contributions_by_year(request_year),
                            'uncommented_contributions': contributions.uncommented().contributions_by_faculty(request.user.profile).contributions_by_year(request_year),
                            'contributions_doc': contributions.contributions_doc().contributions_by_faculty(request.user.profile).contributions_by_year(request_year),
                            'contributions_img': contributions.contributions_img().contributions_by_faculty(request.user.profile).contributions_by_year(request_year),
                            'special_comments': contributions.filter(user_contribution_file__is_special=True).contributions_by_year(request_year),
                            # All Contributions By Faculty
                            'IT_contributions_all': contributions.filter(user__faculty__code__iexact='IT'),
                            'CSE_contributions_all': contributions.filter(user__faculty__code__iexact='CSE'),
                            'SWE_contributions_all': contributions.filter(user__faculty__code__iexact='SWE'),
                            'EEE_contributions_all': contributions.filter(user__faculty__code__iexact='EEE'),
                            # All Contributions By Faculty within each year
                            'IT_contributions': contributions.filter(user__faculty__code__iexact='IT').contributions_by_year(request_year),
                            'CSE_contributions': contributions.filter(user__faculty__code__iexact='CSE').contributions_by_year(request_year),
                            'SWE_contributions': contributions.filter(user__faculty__code__iexact='SWE').contributions_by_year(request_year),
                            'EEE_contributions': contributions.filter(user__faculty__code__iexact='EEE').contributions_by_year(request_year),
                            # All Contributors By Faculty within each year
                            'IT_contributors': contributors.filter(faculty__code__iexact='IT'),
                            'CSE_contributors': contributors.filter(faculty__code__iexact='CSE'),
                            'SWE_contributors': contributors.filter(faculty__code__iexact='SWE'),
                            'EEE_contributors': contributors.filter(faculty__code__iexact='EEE'),
                            # MM Report
                            'contributions_selected_mm': contributions.selected().contributions_by_year(request_year),
                            'uncommented_contributions_mm': contributions.uncommented().contributions_by_year(request_year),

magfetch/templates/snippets/css.html
{% load static %}

<!-- ICON -->
<link rel="icon" href="{% static 'images/icon/favicon.ico' %}" type="image/x-icon" />
<!-- Stylesheets -->
<link rel="stylesheet" href="{% static 'css/md.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css" />
<!-- <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.css' %}" type="text/css" /> -->
<link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap-grid.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap-reboot.css' %}" type="text/css" />
<!-- <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" /> -->
<link rel="stylesheet" href="{% static 'css/animate.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/font.css' %}" type="text/css" />
<!-- <link rel="stylesheet" href="{% static 'js/calendar/bootstrap_calendar.css' %}" type="text/css" /> -->
<link rel="stylesheet" href="{% static 'css/app.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'css/custom.css' %}" type="text/css" />
<!--[if lt IE 9]>
<script src="{% static 'js/ie/html5shiv.js' %}"></script>
<script src="{% static 'js/ie/respond.min.js' %}"></script>
<script src="{% static 'js/ie/excanvas.js' %}"></script>
<![endif]-->
<!-- jQuery -->
<!-- <script src="{% static 'js/jquery.min.js' %}"></script> -->
<script src="{% static 'js/jquery/jquery.min.js' %}"></script>

magfetch/templates/snippets/footer.html
<!-- footer -->
<footer id="footer">
    <div class="text-center padder clearfix">
        <p>
        <small>
            Copyright © {% now "F Y" %} megFetch. All rights reserved. Developed by team
            <span class="text-primary">floppyFive</span>
        </small>
        </p>
    </div>
</footer>
<!-- / footer -->

magfetch/templates/snippets/form.html
{% load widget_tweaks %}

{% if form.visible_fields %}
<div class="text-center m-b-sm">
    <small class="text-muted">
        Please fill the <span class="text-info"><i>required</i></span> fields properly
    </small>
</div>
{% endif %}

{% for hidden_field in form.hidden_fields %}
{% if hidden_field.errors %}
<div class="alert alert-danger" role="alert">
    {% for error in hidden_field.errors %}
    <p class="text-danger font-italic">
        <strong>(Hidden field {{ hidden_field.name }}) {{ error }}</strong>
    </p>
    {% endfor %}
</div>
{% endif %}
{{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
    <p class="text-danger">
        <strong>{{ error }}</strong>
    </p>
    {% endfor %}
</div>
{% endif %}

{% for field in form.visible_fields %}
<div class="form-group" id="{{ field.id_for_label }}-group">

    <label for="{{ field.id_for_label }}" class="control-label" id="{{ field.id_for_label }}-label">
        <strong>{{ field.label |title }}</strong>
        {% if field.field.required %}
        <small class="text-info"><i>(required) </i></small>
        {% else %}
        <small class="text-muted"><i>(optional) </i></small>
        {% endif %}
        {% if field.help_text %}
        <span class="label bg-white" data-toggle="tooltip" data-placement="top" title="" data-original-title="{{ field.help_text|safe }}">
            <i class="fa fa-exclamation-circle"></i>
        </span>
        {% endif %}
    </label>

    <div class="form">
        <!-- Main Input Item -->
        <!-- {{ field.field.widget.input_type }} -->

        {% if field.field.widget.input_type == "file" %}

        {{ field|add_class:'form-control input-sm' }}

        <label for="file-upload" id="file-drag">
            Select a file to upload
            <br />OR-
            <br />Drag a file into this box
            <br /><br />
            <span id="file-upload-btn" class="button">
                Add a file
            </span>
        </label>
        <progress id="file-progress" value="0">
            <span>0</span>%
        </progress>
        <output for="file-upload" id="messages"></output>
        <span id="file-msg" class="text-center font-bold"></span>

        {% else %}

        {{ field|add_class:'form-control input-sm' }}

        {% endif %}

        {% comment %} {% if field.help_text %}
        <div class="help">
            <small id="help_block" class="help-block m-b-none">
                {{ field.help_text|safe }}
            </small>
        </div>
        {% endif %} {% endcomment %}

        {% if field.errors %}
        {% for error in field.errors %}
        <div class="error m-t-sm">
            <b class="text-danger">
                <p id="error-message">{{ error|safe }}</p>
            </b>
        </div>
        {% endfor %}
        {% endif %}

        {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
        {% endif %}
    </div>
    <div class="line line-dashed line-lg pull-in"></div>
</div>

{% endfor %}

magfetch/templates/snippets/header (numan-PC's conflicted copy 2019-04-26).html
{% load static %}
{% url 'home' as home_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_login' as login_url %}
{% url 'account_logout' as logout_url %}

<header class="bg-dark dk header navbar navbar-fixed-top-xs">
    <div class="navbar-header aside-md">
        <a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen,open" data-target="#nav,html">
            <i class="fa fa-bars"></i>
        </a>
        <a href="{% url 'home' %}" class="navbar-brand">
            <img src="{% static 'images/icon/icon.png' %}" class="m-r-sm">
            magFetch
        </a>
        <a class="btn btn-link visible-xs" data-toggle="dropdown" data-target=".nav-user">
            <i class="fa fa-cog"></i>
        </a>
    </div>
    
    {% include 'snippets/chunks/header-left.html' %}

    <ul class="nav navbar-nav navbar-right m-n hidden-xs nav-user">
        {% if notifications.count >= 1 %}
        {% if not notifications == None %}
        <li class="hidden-xs">
            {% include 'snippets/chunks/notification.html' %}
        </li>
        {% endif %}
        {% endif %}
        {% if not request.user.is_authenticated %}
        <li class="dropdown hidden-xs">
            <a href="{{ signup_url }}" class="btn btn-primary btn-xs">
                <i class="fa fa-plus-circle"></i> Signup
            </a>
        </li>
        <li class="dropdown hidden-xs">
            <a href="{{ login_url }}" class="btn btn-success btn-xs">
                <i class="fa fa-location-arrow"></i> Login
            </a>
        </li>
        {% else %}
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <span class="thumb-sm avatar pull-left">
                    <img src="{% static 'images/raw/avatar/avatar.jpg' %}">
                </span>
                {{ user.profile.get_smallname|truncatechars_html:15 }}
            </a>
            <ul class="dropdown-menu animated fadeInRight">
                <span class="arrow top"></span>
                {% if not user.profile.role == None %}
                <li class="text-center m-t-xs">
                    <label class="label bg-info m-l-xs">
                        <i>Role: </i>
                        <span class="text-dark">{{ user.profile.get_role }}</span>
                    </label>
                </li>
                {% if not user.profile.faculty == None %}
                <li class="text-center m-t-xs">
                    <label class="label bg-primary m-l-xs">
                        <i>Faculty:</i>
                        <span class="text-dark">{{ user.profile.faculty.title }}</span>
                    </label>
                </li>
                {% endif %}
                {% endif %}
                <li>
                    <a href="{% url 'utils:notification_list' %}">
                        <i class="fa fa-bell"></i> Notifications
                    </a>
                </li>
                <li>
                    <a href="{% url 'account_change_password' %}">
                        <i class="fa fa-edit"></i> Change Password
                    </a>
                </li>
                <li>
                    <a href="{% url 'account_email' %}">
                        <i class="fa fa-edit"></i> Manage Account Email
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="{{ logout_url }}">Logout</a>
                </li>
            </ul>
        </li>
        {% endif %}
    </ul>
</header>

magfetch/templates/snippets/header.html
{% load static %}
{% url 'home' as home_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_login' as login_url %}
{% url 'account_logout' as logout_url %}

<header class="bg-dark dk header navbar navbar-fixed-top-xs">
    <div class="navbar-header aside-md">
        <a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen,open" data-target="#nav,html">
            <i class="fa fa-bars"></i>
        </a>
        <a href="{% url 'home' %}" class="navbar-brand">
            <img src="{% static 'images/icon/icon.png' %}" class="m-r-sm">
            <span class="logo_text" id="logo-text">magFetch</span>
        </a>
        <a class="btn btn-link visible-xs" data-toggle="dropdown" data-target=".nav-user">
            <i class="fa fa-cog"></i>
        </a>
    </div>

    <!-- CountDown -->
    {% include 'snippets/chunks/countdown.html' %}
    <!-- /CountDown -->

    <ul class="nav navbar-nav navbar-right m-n hidden-xs nav-user">
        {% if not notifications == None %}
        <li class="hidden-xs">
            {% include 'snippets/chunks/notification.html' %}
        </li>
        {% endif %}
        {% if not request.user.is_authenticated %}
        <li class="dropdown hidden-xs">
            <a href="{{ signup_url }}" class="btn btn-primary btn-xs">
                <i class="fa fa-plus-circle"></i> Signup
            </a>
        </li>
        <li class="dropdown hidden-xs">
            <a href="{{ login_url }}" class="btn btn-success btn-xs">
                <i class="fa fa-location-arrow"></i> Login
            </a>
        </li>
        {% else %}
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <span class="thumb-sm avatar pull-left">
                    <img src="{% static 'images/raw/avatar/avatar.jpg' %}">
                </span>
                {{ user.profile.get_smallname|truncatechars_html:15 }}
            </a>
            <ul class="dropdown-menu animated fadeInRight">
                <span class="arrow top"></span>
                {% if not user.profile.role == None %}
                <li class="text-center m-t-xs">
                    <label class="label bg-info m-l-xs">
                        <i>Role: </i>
                        <span class="text-dark">{{ user.profile.get_role }}</span>
                    </label>
                </li>
                {% if not user.profile.faculty == None %}
                <li class="text-center m-t-xs">
                    <label class="label bg-primary m-l-xs">
                        <i>Faculty:</i>
                        <span class="text-dark">{{ user.profile.faculty.title }}</span>
                    </label>
                </li>
                {% endif %}
                {% endif %}
                <li>
                    <a href="{% url 'utils:notification_list' %}">
                        <i class="fa fa-bell"></i> Notifications
                    </a>
                </li>
                <li>
                    <a href="{% url 'account_change_password' %}">
                        <i class="fa fa-edit"></i> Change Password
                    </a>
                </li>
                <li>
                    <a href="{% url 'account_email' %}">
                        <i class="fa fa-edit"></i> Manage Account Email
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="{{ logout_url }}">Logout</a>
                </li>
            </ul>
        </li>
        {% endif %}
    </ul>
</header>

magfetch/templates/snippets/meta_tags.html
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="magfetch, magazine, management system, university, app, web app, responsive" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" /> 
<meta name="copyright" content="magfetch.herokuapp.com">
<meta name="keywords" content="magfetch, management system, Numan Ibn Mazid, Numan, Bangladesh, BD, com, org, domain, google, linkedin, Numan, Law firm, Youtube, magfetch, magfetch.com, herokuapp, python, django, magazine, company">
<meta name="author" content="Numan Ibn Mazid">
<!-- <meta http-equiv="cache-control" content="no-cache" />
<meta name="robots" content="noindex,nofollow">
<meta http-equiv="refresh" content="777">
<meta property="og:type" content="magfetch" />
<meta property="og:url" content="https://magfetch.herokuapp.com/" />
<meta property="og:title" content="magFetch" />
<meta property="og:site_name" content="magFetch" />
<meta property="og:image" content="https://magfetch.herokuapp.com/static/images/icon/icon.png" />
<meta name="referrer" content="origin-when-crossorigin"> -->
<!-- This Force to Browse in HTTPS Mode -->
<!-- <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"> -->

magfetch/templates/snippets/sidebar.html
{% load static %}
{% url 'home' as home_url %}
{% url 'statistics_search' as home_fake_url %}
{% url 'system_data:date_create' as date_create_url %}
{% url 'system_data:date_update' as date_update_url %}
{% url 'contribution:category_create' as category_create_url %}
{% url 'contribution:contribution_list' as contribution_list_url %}
{% url 'contribution:selected_contribution_list' as selected_contribution_list_url %}


<!-- Clock CSS -->
<link rel="stylesheet" href="{% static 'vendor/clock/clock.css' %}" type="text/css" />

<aside class="bg-c-smoke lter aside-md hidden-print" id="nav">
    <section class="vbox">
        <section class="w-f scrollable">
            <div class="slim-scroll" data-height="auto" data-disable-fade-out="true" data-distance="0" data-size="5px"
                data-color="#333333">

                <!-- nav -->
                <nav class="nav-primary hidden-xs">
                    <ul class="nav">
                        <li
                            class="{% if request.path == home_url or request.path == home_fake_url %} active {% endif %}">
                            <a href="{{ home_url }}">
                                <i class="fa fa-dashboard icon">
                                    <b class="bg-danger"></b>
                                </i>
                                <span>Home</span>
                            </a>
                        </li>
                        {% if is_AD %}
                        {% if get_schedule == None %}
                        <li class="{% if request.path == date_create_url %} active {% endif %}">
                            <a href="{{ date_create_url }}">
                                <i class="fa fa-pencil icon">
                                    <b class="bg-info"></b>
                                </i>
                                <span>Create Schedule</span>
                            </a>
                        </li>
                        {% else %}
                        <li class="{% if request.path == date_update_url %} active {% endif %}">
                            <a href="{{ date_update_url }}">
                                <i class="fa fa-pencil icon">
                                    <b class="bg-info"></b>
                                </i>
                                <span>Update Schedule</span>
                            </a>
                        </li>
                        {% endif %}

                        <li class="{% if request.path == category_create_url %} active {% endif %}">
                            <a href="{{ category_create_url }}">
                                <i class="fa fa-pencil icon">
                                    <b class="bg-info"></b>
                                </i>
                                <span>Contribution Category</span>
                            </a>
                        </li>
                        {% endif %}

                        {% if is_MC %}
                        <li class="{% if request.path == contribution_list_url %} active {% endif %}">
                            <a href="{{ contribution_list_url }}">
                                <i class="fa fa-file-text icon">
                                    <b class="bg-info"></b>
                                </i>
                                <span>Contributions</span>
                            </a>
                        </li>
                        {% endif %}

                        {% if is_MM %}
                        <li class="{% if request.path == selected_contribution_list_url %} active {% endif %}">
                            <a href="{{ selected_contribution_list_url }}">
                                <i class="fa fa-file-text icon">
                                    <b class="bg-info"></b>
                                </i>
                                <span>Selected Contributions</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
                <!-- / nav -->
            </div>
        </section>

        <footer class="footer lt hidden-xs b-t b-dark">
            <a href="#nav" data-toggle="class:nav-xs" class="pull-right btn btn-sm btn-dark btn-icon">
                <!-- Digital Clock -->
                <div class="digital-clock">00:00:00</div>
                <!-- //Digital Clock -->
                <i class="fa fa-angle-left text"></i>
                <i class="fa fa-angle-right text-active"></i>
                <i id="copy">©️FlopyFive</i>
            </a>
        </footer>
    </section>
</aside>

<!-- Clock JS -->
<script src="{% static 'vendor/clock/clock.js' %}"></script>