magfetch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView, statistics_search
from .routers import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('account/', include('accounts.urls')),
    path('system/data/', include(('system_data.urls', 'system_data'), namespace='system_data')),
    path('utils/', include(('utils.urls', 'utils'), namespace='utils')),
    path('contribution/', include(('contribution.urls', 'contribution'), namespace='contribution')),
    path('api/', include(router.urls)),
    path('statistics/search/', statistics_search, name='statistics_search')
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

utils/urls.py
from django.urls import path
from .views import AnnouncementDetailView, NotificationDetailView, NotificationListView, mark_all_as_read

urlpatterns = [
    path('announcement/<slug>/detail/', AnnouncementDetailView.as_view(), name='announcement_detail'),
    path('notification/list/', NotificationListView.as_view(), name='notification_list'),
    path('notification/<slug>/detail/', NotificationDetailView.as_view(), name='notification_detail'),
    path('notification/all/read/', mark_all_as_read, name='mark_all_as_read')
]

magfetch/views.py
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import render
from accounts.models import UserProfile
from contribution.models import Contribution, Comment
from django.db.models import Q
from django.contrib import messages
import datetime
import re

# @method_decorator(login_required, name='dispatch')
# class HomeView(TemplateView):
#     template_name = 'pages/home.html'


@method_decorator(login_required, name='dispatch')
class HomeView(TemplateView):
    def get(self, request, *args, **kwargs):
        user = request.user
        today = datetime.datetime.now()
        user_profile_filter = UserProfile.objects.filter(user=user)
        if user_profile_filter.exists():
            profile = user_profile_filter.first()
            # -------- Administrative Dashboard View -----------
            if profile.role == 0 or profile.role == 1 or profile.role == 2 or profile.role == 3:
                contributions = Contribution.objects.all().latest()
                contributors = UserProfile.objects.filter(~Q(user_contribution=None)).exclude(~Q(user_contribution__created_at__year=today.year))
                context = {
                    'contributions': contributions,
                    'contributions_this_year': contributions.contributions_this_year(),
                    'contributions_selected': contributions.selected().contributions_by_faculty(request.user.profile).contributions_this_year(),
                    'uncommented_contributions': contributions.uncommented().contributions_by_faculty(request.user.profile).contributions_this_year(),
                    'contributions_doc': contributions.contributions_doc().contributions_by_faculty(request.user.profile).contributions_this_year(),
                    'contributions_img': contributions.contributions_img().contributions_by_faculty(request.user.profile).contributions_this_year(),
                    'special_comments': contributions.filter(user_contribution_file__is_special=True).contributions_this_year(),
                    # All Contributions By Faculty
                    'IT_contributions_all': contributions.filter(user__faculty__code__iexact='IT'),
                    'CSE_contributions_all': contributions.filter(user__faculty__code__iexact='CSE'),
                    'SWE_contributions_all': contributions.filter(user__faculty__code__iexact='SWE'),
                    'EEE_contributions_all': contributions.filter(user__faculty__code__iexact='EEE'),
                    # All Contributions By Faculty within each year
                    'IT_contributions': contributions.filter(user__faculty__code__iexact='IT').contributions_this_year(),
                    'CSE_contributions': contributions.filter(user__faculty__code__iexact='CSE').contributions_this_year(),
                    'SWE_contributions': contributions.filter(user__faculty__code__iexact='SWE').contributions_this_year(),
                    'EEE_contributions': contributions.filter(user__faculty__code__iexact='EEE').contributions_this_year(),
                    # All Contributors By Faculty within each year
                    'IT_contributors': contributors.filter(faculty__code__iexact='IT'),
                    'CSE_contributors': contributors.filter(faculty__code__iexact='CSE'),
                    'SWE_contributors': contributors.filter(faculty__code__iexact='SWE'),
                    'EEE_contributors': contributors.filter(faculty__code__iexact='EEE'),
                    # MM Report
                    'contributions_selected_mm': contributions.selected().contributions_this_year(),
                    'uncommented_contributions_mm': contributions.uncommented().contributions_this_year(),
                    'special_comments_mm': contributions.filter(user_contribution_file__is_special=True).contributions_by_year(today.year),
                    'contributions_doc_mm': contributions.contributions_doc().contributions_this_year(),
                    'contributions_img_mm': contributions.contributions_img().contributions_this_year(),
                    # Extra
                    'input_value':today.year,
                    'contributions_by_year': contributions.contributions_by_year(today.year),
                    'contributions_by_year_faculty': contributions.contributions_by_year(today.year).contributions_by_faculty(request.user.profile),
                    'contributors_by_year': contributors
                }
                return render(request, "pages/home.html", context=context)
            # ------- Student Landing Page View -------
            if profile.role == 4:
                # If submited check
                submitted_filter = Contribution.objects.filter(
                    user=profile, updated_at__year=today.year)
                if submitted_filter.exists():
                    is_submitted = True
                else:
                    is_submitted = False
                context = {
                    'is_submitted': is_submitted,
                    'contributions': submitted_filter
                }
                return render(request, "landing/pages/home.html", context=context)
            # ------- Django Admin View -------
            if profile.user.is_staff == True:
                return render(request, "pages/home.html")
            # ------- Anonymous View -------
            if profile.role == 7:
                return render(request, "anonymous.html")
        return render(request, "anonymous.html")


def statistics_search(request):
    user = request.user
    user_profile_filter = UserProfile.objects.filter(user=user)
    today = datetime.datetime.now()
    if user_profile_filter.exists():
        profile = user_profile_filter.first()
        # -------- Administrative Dashboard View -----------
        if profile.role == 0 or profile.role == 1 or profile.role == 2 or profile.role == 3:
            request_year = today.year
            if request.method == 'POST':
                request_year = request.POST.get('contribution_search')
                if not request_year == None:
                    allowed_chars = re.match(r'^[0-9]+$', request_year)
                    length = len(request_year)
                    if not allowed_chars or length >= 5:
                        messages.add_message(request, messages.WARNING,
                             "Please enter valid year!!!")
                        context = {
                            'error': True,
                            'input_value':today.year
                        }
                        return render(request, "pages/home.html", context=context)
                    else:
                        contributions = Contribution.objects.all().latest()
                        contributors = UserProfile.objects.filter(~Q(user_contribution=None)).exclude(~Q(user_contribution__created_at__year=request_year))
                        context = {
                            'contributions': contributions,
                            'contributions_this_year': contributions.contributions_this_year(),
                            'contributions_selected': contributions.selected().contributions_by_faculty(request.user.profile).contributions_by_year(request_year),
                            'uncommented_contributions': contributions.uncommented().contributions_by_faculty(request.user.profile).contributions_by_year(request_year),
                            'contributions_doc': contributions.contributions_doc().contributions_by_faculty(request.user.profile).contributions_by_year(request_year),
                            'contributions_img': contributions.contributions_img().contributions_by_faculty(request.user.profile).contributions_by_year(request_year),
                            'special_comments': contributions.filter(user_contribution_file__is_special=True).contributions_by_year(request_year),
                            # All Contributions By Faculty
                            'IT_contributions_all': contributions.filter(user__faculty__code__iexact='IT'),
                            'CSE_contributions_all': contributions.filter(user__faculty__code__iexact='CSE'),
                            'SWE_contributions_all': contributions.filter(user__faculty__code__iexact='SWE'),
                            'EEE_contributions_all': contributions.filter(user__faculty__code__iexact='EEE'),
                            # All Contributions By Faculty within each year
                            'IT_contributions': contributions.filter(user__faculty__code__iexact='IT').contributions_by_year(request_year),
                            'CSE_contributions': contributions.filter(user__faculty__code__iexact='CSE').contributions_by_year(request_year),
                            'SWE_contributions': contributions.filter(user__faculty__code__iexact='SWE').contributions_by_year(request_year),
                            'EEE_contributions': contributions.filter(user__faculty__code__iexact='EEE').contributions_by_year(request_year),
                            # All Contributors By Faculty within each year
                            'IT_contributors': contributors.filter(faculty__code__iexact='IT'),
                            'CSE_contributors': contributors.filter(faculty__code__iexact='CSE'),
                            'SWE_contributors': contributors.filter(faculty__code__iexact='SWE'),
                            'EEE_contributors': contributors.filter(faculty__code__iexact='EEE'),
                            # MM Report
                            'contributions_selected_mm': contributions.selected().contributions_by_year(request_year),
                            'uncommented_contributions_mm': contributions.uncommented().contributions_by_year(request_year),

magfetch/templates/pages/snippets/chunks/announcement.html
<section class="panel panel-default">
  <header class="panel-heading">
    <span class="label bg-dark">{{ get_announcement.count }}</span> Announcements
  </header>
  <section class="panel-body slim-scroll" data-height="110px">
    {% for announcement in get_announcement %}
    {% if announcement.status == 0 %}
    <article class="media">
      <span class="pull-left thumb-sm">
        <i class="fa fa-bullhorn font-25"></i>
      </span>
      <div class="media-body">
        <a href="{% url 'utils:announcement_detail' slug=announcement.slug %}" class="h5">
          <strong>
            {{ announcement.subject }}
          </strong>
        </a>
        <small class="block m-t-sm">
          {{ announcement.message|safe|truncatechars_html:66 }}
        </small>
        <div class="pull-right media-xs text-center text-muted">
          <strong class="h4"></strong><br>
          <small class="label bg-light">{{ announcement.updated_at|timesince }} ago</small>
        </div>
      </div>
    </article>
    {% endif %}
    {% empty %}
    <span class="text-dark">There is no Announcement to show !</span>
    {% endfor %}
    <div class="line pull-in"></div>
  </section>
</section>

magfetch/templates/pages/snippets/chunks/comment.html
<!-- .comment-list -->
<section class="comment-list block">
  <article id="comment-id-1" class="comment-item">
    <a class="pull-left thumb-sm avatar">
      <img src="images/avatar.jpg" class="img-circle">
    </a>
    <span class="arrow left"></span>
    <section class="comment-body panel panel-default">
      <header class="panel-heading bg-white">
        <a href="#">John smith</a>
        <label class="label bg-info m-l-xs">Editor</label>
        <span class="text-muted m-l-sm pull-right">
          <i class="fa fa-clock-o"></i>
          Just now
        </span>
      </header>
      <div class="panel-body">
        <div>Lorem ipsum dolor sit amet, consecteter adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet.</div>
        <div class="comment-action m-t-sm">
          <a href="#" data-toggle="class" class="btn btn-default btn-xs active">
            <i class="fa fa-star-o text-muted text"></i>
            <i class="fa fa-star text-danger text-active"></i>
            Like
          </a>
          <a href="#comment-form" class="btn btn-default btn-xs">
            <i class="fa fa-mail-reply text-muted"></i> Reply
          </a>
        </div>
      </div>
    </section>
  </article>
  <!-- .comment-reply -->
  <article id="comment-id-2" class="comment-item comment-reply">
    <a class="pull-left thumb-sm avatar">
      <img src="images/avatar.jpg" class="img-circle">
    </a>
    <span class="arrow left"></span>
    <section class="comment-body panel panel-default text-sm">
      <div class="panel-body">
        <span class="text-muted m-l-sm pull-right">
          <i class="fa fa-clock-o"></i>
          10m ago
        </span>
        <a href="#">Mika Sam</a>
        <label class="label bg-dark m-l-xs">Admin</label>
        Report this comment is helpful
      </div>
    </section>
  </article>
  <!-- / .comment-reply -->
  <article id="comment-id-3" class="comment-item">
    <a class="pull-left thumb-sm avatar"><img src="images/avatar.jpg" class="img-circle"></a>
    <span class="arrow left"></span>
    <section class="comment-body panel panel-default">
      <header class="panel-heading">
        <a href="#">By me</a>
        <label class="label bg-success m-l-xs">User</label>
        <span class="text-muted m-l-sm pull-right">
          <i class="fa fa-clock-o"></i>
          1h ago
        </span>
      </header>
      <div class="panel-body">
        <div>This comment was posted by you.</div>
        <div class="comment-action m-t-sm">
          <a href="#comment-id-3" data-dismiss="alert" class="btn btn-default btn-xs">
            <i class="fa fa-trash-o text-muted"></i>
            Remove
          </a>
        </div>
      </div>
    </section>
  </article>
  <article id="comment-id-4" class="comment-item">
    <a class="pull-left thumb-sm avatar"><img src="images/avatar.jpg" class="img-circle"></a>
    <span class="arrow left"></span>
    <section class="comment-body panel panel-default">
      <header class="panel-heading">
        <a href="#">Peter</a>
        <label class="label bg-primary m-l-xs">Vip</label>
        <span class="text-muted m-l-sm pull-right">
          <i class="fa fa-clock-o"></i>
          2hs ago
        </span>
      </header>
      <div class="panel-body">
        <blockquote>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
          <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
        </blockquote>
        <div>Lorem ipsum dolor sit amet, consecteter adipiscing elit...</div>
        <div class="comment-action m-t-sm">
          <a href="#" data-toggle="class" class="btn btn-default btn-xs">
            <i class="fa fa-star-o text-muted text"></i>
            <i class="fa fa-star text-danger text-active"></i>
            Like
          </a>
          <a href="#comment-form" class="btn btn-default btn-xs"><i class="fa fa-mail-reply text-muted"></i> Reply</a>
        </div>
      </div>
    </section>
  </article>
  <!-- comment form -->
  <article class="comment-item media" id="comment-form">
    <a class="pull-left thumb-sm avatar"><img src="images/avatar.jpg" class="img-circle"></a>
    <section class="media-body">
      <form action="" class="m-b-none">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Input your comment here">
          <span class="input-group-btn">
            <button class="btn btn-primary" type="button">POST</button>
          </span>
        </div>
      </form>
    </section>
  </article>
</section>
<!-- / .comment-list -->

magfetch/templates/pages/snippets/chunks/contribution-percentage.html
<section class="panel panel-default">
    <header class="panel-heading font-bold">Contribtions (All Time)
        {% if IT_contributions_all.count == 0 and CSE_contributions_all.count == 0 and SWE_contributions_all.count == 0 and EEE_contributions_all.count == 0 %}
        <span class="badge badge-warning pull-right c-text-warning">No Data Found !!!</span>
        {% endif %}
        {% if not contributions.count == 0 %}
        <span class="badge badge-dark pull-right c-text-dark">{{contributions.count}}</span>
        {% endif %}
    </header>
    <div class="text-center wrapper bg-light lt">
        <!-- <div class="sparkline inline" data-type="pie" data-height="165" data-slice-colors="['#77c587','#41586e','#f2f2f2']">45000,23200,15000</div> -->
        <div class="sparkline inline" data-type="pie" data-height="165"
            data-slice-colors="['#77c587','#41586e','#f2f2f2','#4CC0C1']">
            {{IT_contributions_all.count}},{{CSE_contributions_all.count}},{{SWE_contributions_all.count}},{{EEE_contributions_all.count}}
        </div>
    </div>
    <ul class="list-group no-radius">
        <li class="list-group-item">
            <span class="pull-right">{{IT_contributions_all.count}}</span>
            <span class="label bg-primary">1</span>
            IT
        </li>
        <li class="list-group-item">
            <span class="pull-right">{{CSE_contributions_all.count}}</span>
            <span class="label bg-dark">2</span>
            CSE
        </li>
        <li class="list-group-item">
            <span class="pull-right">{{SWE_contributions_all.count}}</span>
            <span class="label bg-light">3</span>
            SWE
        </li>
        <li class="list-group-item">
            <span class="pull-right">{{EEE_contributions_all.count}}</span>
            <span class="label bg-info">4</span>
            EEE
        </li>
    </ul>
</section>

magfetch/templates/pages/snippets/chunks/contributions-each-year.html
<section class="panel panel-default">
    <header class="panel-heading font-bold">Contribtions ({{input_value}})
        {% if IT_contributions.count == 0 and CSE_contributions.count == 0 and SWE_contributions.count == 0 and EEE_contributions.count == 0 %}
        <span class="badge badge-warning pull-right c-text-warning">No Data Found !!!</span>
        {% endif %}
        {% if not contributions_by_year.count == 0 %}
        <span class="badge badge-dark pull-right c-text-dark">{{contributions_by_year.count}}</span>
        {% endif %}
    </header>
    <div class="text-center wrapper bg-light lt">
        <!-- <div class="sparkline inline" data-type="pie" data-height="165" data-slice-colors="['#77c587','#41586e','#f2f2f2']">45000,23200,15000</div> -->
        <div class="sparkline inline" data-type="pie" data-height="165"
            data-slice-colors="['#77c587','#41586e','#f2f2f2','#4CC0C1']">
            {{IT_contributions.count}},{{CSE_contributions.count}},{{SWE_contributions.count}},{{EEE_contributions.count}}
        </div>
    </div>
    <ul class="list-group no-radius">
        <li class="list-group-item">
            <span class="pull-right">{{IT_contributions.count}}</span>
            <span class="label bg-primary">1</span>
            IT
        </li>
        <li class="list-group-item">
            <span class="pull-right">{{CSE_contributions.count}}</span>
            <span class="label bg-dark">2</span>
            CSE
        </li>
        <li class="list-group-item">
            <span class="pull-right">{{SWE_contributions.count}}</span>
            <span class="label bg-light">3</span>
            SWE
        </li>
        <li class="list-group-item">
            <span class="pull-right">{{EEE_contributions.count}}</span>
            <span class="label bg-info">4</span>
            EEE
        </li>
    </ul>
</section>

magfetch/templates/pages/snippets/chunks/contributions_catwise_by_faculty.html
<div class="panel-group m-b" id="accordion2">
    <div class="panel panel-default">
        <div class="panel-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#contribution_selected">
                Contributions
                <span class="c-text-warning">(Selected)</span>
                <span class="badge bg-dark c-text-info">{{ contributions_selected.count }}</span>
            </a>
        </div>
        <div id="contribution_selected" class="panel-collapse collapse" style="height: 0px;">
            <div class="panel-body text-sm">
                {% include 'contribution/list-common.html' with dynamic_variable=contributions_selected dynamic_datatable='dynamic_datatable1' %}
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2"
                href="#contribution_docs">
                Contributions
                <span class="c-text-warning">(Documents)</span>
                <span class="badge bg-dark c-text-info">{{ contributions_doc.count }}</span>
            </a>
        </div>
        <div id="contribution_docs" class="panel-collapse collapse">
            <div class="panel-body text-sm">
                {% include 'contribution/list-common.html' with dynamic_variable=contributions_doc dynamic_datatable='dynamic_datatable2' %}
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#contribution_images">
                Contributions
                <span class="c-text-warning">(Images)</span>
                <span class="badge bg-dark c-text-info">{{ contributions_img.count }}</span>
            </a>
        </div>
        <div id="contribution_images" class="panel-collapse collapse">
            <div class="panel-body text-sm">
                {% include 'contribution/list-common.html' with dynamic_variable=contributions_img dynamic_datatable='dynamic_datatable3' %}
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#contributions_uncommented">
                Contributions
                <span class="c-text-warning">(Without Comment)</span>
                <span class="badge bg-dark c-text-info">{{ uncommented_contributions.count }}</span>
            </a>
        </div>
        <div id="contributions_uncommented" class="panel-collapse collapse" style="height: 0px;">
            <div class="panel-body text-sm">
                {% include 'contribution/list-common.html' with dynamic_variable=uncommented_contributions dynamic_datatable='dynamic_datatable4' %}
            </div>
        </div>
    </div>
</div>

<script>
$('#contributions_uncommented').on('shown.bs.collapse', function () {
    $($.fn.dataTable.tables(true)).DataTable()
        .columns.adjust();
});
$('#contribution_selected').on('shown.bs.collapse', function () {
    $($.fn.dataTable.tables(true)).DataTable()
        .columns.adjust();
});
$('#contribution_docs').on('shown.bs.collapse', function () {
    $($.fn.dataTable.tables(true)).DataTable()
        .columns.adjust();
});
$('#contribution_images').on('shown.bs.collapse', function () {
    $($.fn.dataTable.tables(true)).DataTable()
        .columns.adjust();
});
</script>

magfetch/templates/pages/snippets/chunks/contributors-each-year.html
<section class="panel panel-default">
    <header class="panel-heading font-bold">Contributors ({{input_value}})
        {% if IT_contributions.count == 0 and CSE_contributions.count == 0 and SWE_contributions.count == 0 and EEE_contributions.count == 0 %}
        <span class="badge badge-warning pull-right c-text-warning">No Data Found !!!</span>
        {% endif %}
        {% if not contributors_by_year.count == 0 %}
        <span class="badge badge-dark pull-right c-text-dark">{{contributors_by_year.count}}</span>
        {% endif %}
    </header>
    <div class="text-center wrapper bg-light lt">
        <!-- <div class="sparkline inline" data-type="pie" data-height="165" data-slice-colors="['#77c587','#41586e','#f2f2f2']">45000,23200,15000</div> -->
        <div class="sparkline inline" data-type="pie" data-height="165"
            data-slice-colors="['#77c587','#41586e','#f2f2f2','#4CC0C1']">
            {{IT_contributors.count}},{{CSE_contributors.count}},{{SWE_contributors.count}},{{EEE_contributors.count}}
        </div>
    </div>
    <ul class="list-group no-radius">
        <li class="list-group-item">
            <span class="pull-right">{{IT_contributors.count}}</span>
            <span class="label bg-primary">1</span>
            IT
        </li>
        <li class="list-group-item">
            <span class="pull-right">{{CSE_contributors.count}}</span>
            <span class="label bg-dark">2</span>
            CSE
        </li>
        <li class="list-group-item">
            <span class="pull-right">{{SWE_contributors.count}}</span>
            <span class="label bg-light">3</span>
            SWE
        </li>
        <li class="list-group-item">
            <span class="pull-right">{{EEE_contributors.count}}</span>
            <span class="label bg-info">4</span>
            EEE
        </li>
    </ul>
</section>