contribution/urls.py
from django.urls import path
from .views import (
    ContributionCategoryCreateView,
    ContributionCategoryUpdateView,
    ContributionCategoryDeleteView,
    ContributionUploadView,
    ContributionListView,
    ContributionDetailView,
    SelectedContributionListView,
    mark_as_selected,
    mark_as_unselected,
    contribution_delete,
    comment_create,
    CommentListView
)

urlpatterns = [
    # Contribution Category
    path('category/create/', ContributionCategoryCreateView.as_view(),
         name='category_create'),
    path('category/<slug>/update/', ContributionCategoryUpdateView.as_view(),
         name='category_update'),
    path('category/<slug>/delete/', ContributionCategoryDeleteView.as_view(),
         name='category_delete'),
    # Contribution
    path('upload/', ContributionUploadView.as_view(), name='upload'),
    path('delete/', contribution_delete, name='contribution_delete'),
    path('<slug>/detail/', ContributionDetailView.as_view(), name='contribution_detail'),
    path('list/', ContributionListView.as_view(), name='contribution_list'),
    path('selected/list/', SelectedContributionListView.as_view(), name='selected_contribution_list'),
    path('<slug>/mark/selected/', mark_as_selected, name='contribution_selected'),
    path('<slug>/mark/unselected/', mark_as_unselected, name='contribution_unselected'),
    #comment
    path('comment/<slug>/create/', comment_create, name='comment_create'),
    path('comment/<slug>/view/', CommentListView.as_view(), name='comment_view'),
]

magfetch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView, statistics_search
from .routers import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('account/', include('accounts.urls')),
    path('system/data/', include(('system_data.urls', 'system_data'), namespace='system_data')),
    path('utils/', include(('utils.urls', 'utils'), namespace='utils')),
    path('contribution/', include(('contribution.urls', 'contribution'), namespace='contribution')),
    path('api/', include(router.urls)),
    path('statistics/search/', statistics_search, name='statistics_search')
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

utils/urls.py
from django.urls import path
from .views import AnnouncementDetailView, NotificationDetailView, NotificationListView, mark_all_as_read

urlpatterns = [
    path('announcement/<slug>/detail/', AnnouncementDetailView.as_view(), name='announcement_detail'),
    path('notification/list/', NotificationListView.as_view(), name='notification_list'),
    path('notification/<slug>/detail/', NotificationDetailView.as_view(), name='notification_detail'),
    path('notification/all/read/', mark_all_as_read, name='mark_all_as_read')
]

contribution/views.py
from django.shortcuts import render, redirect, get_object_or_404
# Models Import
from .models import ContributionCategory, Contribution, Comment
from accounts.models import UserProfile
from system_data.models import Date
from suspicious.models import Suspicious
# Form import
from .forms import (
    ContributionCategoryCreateForm,
    ContributionUploadForm,
)
# generic view import
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
# other import
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse
from django.core.paginator import Paginator
from django import forms
from django.contrib import messages
import datetime
from .handlers import create_notification_to_mc_upload
from django.core.mail import EmailMultiAlternatives
from django.core.files.storage import default_storage
import os
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse 
from accounts.utils import get_client_ip
from uuid import getnode as get_mac



# Contribution Category Create View
@method_decorator(login_required, name='dispatch')
class ContributionCategoryCreateView(CreateView):
    template_name = 'category/create.html'
    form_class = ContributionCategoryCreateForm

    def form_valid(self, form):
        title = form.instance.title
        category_for = form.instance.category_for
        # category_for = form.instance.category_for
        qs = ContributionCategory.objects.filter(
            title__iexact=title, category_for=category_for)
        if qs.exists():
            form.add_error(
                'title', forms.ValidationError(
                    "This Category is alreay exists! Please try another one."
                )
            )
            return super().form_invalid(form)
        else:
            messages.add_message(self.request, messages.SUCCESS,
                                 "Category has been added successfully!")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('contribution:category_create')

    def get_context_data(self, **kwargs):
        context = super(ContributionCategoryCreateView,
                        self).get_context_data(**kwargs)
        doc_category = ContributionCategory.objects.filter(
            category_for=0).order_by('-created_at')
        img_category = ContributionCategory.objects.filter(
            category_for=1).order_by('-created_at')
        context['doc_categories'] = doc_category
        context['doc_categories_count'] = doc_category.count()
        context['img_categories'] = img_category
        context['img_categories_count'] = img_category.count()
        return context

    def user_passes_test(self, request):
        user = request.user
        if UserProfile.objects.filter(user=user).first().role == 1:
            return True
        return False

    def dispatch(self, request, *args, **kwargs):
        instance_user = self.request.user
        if not self.user_passes_test(request):
            suspicious_user = Suspicious.objects.filter(user=instance_user)
            if suspicious_user.exists():
                suspicious_user_instance = Suspicious.objects.get(
                    user=instance_user)
                current_attempt = suspicious_user_instance.attempt
                total_attempt = current_attempt + 1
                update_time = datetime.datetime.now()
                suspicious_user.update(
                    attempt=total_attempt, last_attempt=update_time)
            else:
                client_ip = get_client_ip(request)
                client_mac = get_mac()
                Suspicious.objects.get_or_create(user=instance_user, ip=client_ip, mac=client_mac)
            messages.add_message(self.request, messages.ERROR,
                                 "You are not allowed. Your account is being tracked for suspicious activity !"
                                 )
            return HttpResponseRedirect(reverse('home'))
        return super(ContributionCategoryCreateView, self).dispatch(request, *args, **kwargs)


# Contribution Category Update View
@method_decorator(login_required, name='dispatch')
class ContributionCategoryUpdateView(UpdateView):
    template_name = 'category/update.html'
    form_class = ContributionCategoryCreateForm

    def get_object(self):
        slug = self.kwargs['slug']
        qs = ContributionCategory.objects.filter(slug=slug)
        if qs.exists():
            return qs.first()
        return None

    def form_valid(self, form):
        pre = self.get_object()
        title = form.instance.title
        category_for = form.instance.category_for
        if not pre.title == title:
            qs = ContributionCategory.objects.filter(
                title__iexact=title, category_for=category_for)
            if qs.exists():
                form.add_error(
                    'title', forms.ValidationError(
                        "This Category is alreay exists! Please try another one."
                    )
                )
                return super().form_invalid(form)
        messages.add_message(self.request, messages.SUCCESS,
                             "Category has been added successfully!")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('contribution:category_create')

    def get_context_data(self, **kwargs):
        context = super(ContributionCategoryUpdateView,
                        self).get_context_data(**kwargs)
        doc_category = ContributionCategory.objects.filter(
            category_for=0).order_by('-created_at')
        img_category = ContributionCategory.objects.filter(
            category_for=1).order_by('-created_at')
        context['doc_categories'] = doc_category
        context['doc_categories_count'] = doc_category.count()
        context['img_categories'] = img_category
        context['img_categories_count'] = img_category.count()
        return context

    def user_passes_test(self, request):
        user = request.user
        if UserProfile.objects.filter(user=user).first().role == 1:
            return True
        return False

    def dispatch(self, request, *args, **kwargs):
        instance_user = self.request.user
        if not self.user_passes_test(request):
            suspicious_user = Suspicious.objects.filter(user=instance_user)
            if suspicious_user.exists():
                suspicious_user_instance = Suspicious.objects.get(
                    user=instance_user)
                current_attempt = suspicious_user_instance.attempt
                total_attempt = current_attempt + 1
                update_time = datetime.datetime.now()
                suspicious_user.update(
                    attempt=total_attempt, last_attempt=update_time)
            else:
                client_ip = get_client_ip(request)
                client_mac = get_mac()
                Suspicious.objects.get_or_create(user=instance_user, ip=client_ip, mac=client_mac)
            messages.add_message(self.request, messages.ERROR,
                                 "You are not allowed. Your account is being tracked for suspicious activity !"
                                 )
            return HttpResponseRedirect(reverse('home'))
        return super(ContributionCategoryUpdateView, self).dispatch(request, *args, **kwargs)


# Contribution Category Delete View
@method_decorator(login_required, name='dispatch')
class ContributionCategoryDeleteView(DeleteView):
    template_name = 'category/delete.html'
    form_class = ContributionCategoryCreateForm

    def get_object(self):
        slug = self.kwargs['slug']
        qs = ContributionCategory.objects.filter(slug=slug)
        if qs.exists():
            return qs.first()
        return None

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS,
                             "Category has been deleted successfully!")
        return reverse('contribution:category_create')

    def get_context_data(self, **kwargs):
        context = super(ContributionCategoryDeleteView,
                        self).get_context_data(**kwargs)
        doc_category = ContributionCategory.objects.filter(
            category_for=0).order_by('-created_at')
        img_category = ContributionCategory.objects.filter(
            category_for=1).order_by('-created_at')
        context['doc_categories'] = doc_category
        context['doc_categories_count'] = doc_category.count()
        context['img_categories'] = img_category
        context['img_categories_count'] = img_category.count()
        return context

    def user_passes_test(self, request):
        user = request.user
        if UserProfile.objects.filter(user=user).first().role == 1:
            return True
        return False

    def dispatch(self, request, *args, **kwargs):
        instance_user = self.request.user
        if not self.user_passes_test(request):
            suspicious_user = Suspicious.objects.filter(user=instance_user)
            if suspicious_user.exists():
                suspicious_user_instance = Suspicious.objects.get(
                    user=instance_user)
                current_attempt = suspicious_user_instance.attempt
                total_attempt = current_attempt + 1
                update_time = datetime.datetime.now()
                suspicious_user.update(
                    attempt=total_attempt, last_attempt=update_time)
            else:
                client_ip = get_client_ip(request)
                client_mac = get_mac()
                Suspicious.objects.get_or_create(user=instance_user, ip=client_ip, mac=client_mac)
            messages.add_message(self.request, messages.ERROR,
                                 "You are not allowed. Your account is being tracked for suspicious activity !"

magfetch/templates/landing/pages/snippets/chunks/coming-slider.html
<section class="panel panel-default">
    <div class="carousel slide auto panel-body" id="c-slide">
        <ol class="carousel-indicators out">
            <li data-target="#c-slide" data-slide-to="0" class="active"></li>
            <li data-target="#c-slide" data-slide-to="1" class=""></li>
        </ol>
        <div class="carousel-inner">
            <div class="item active">
                <p class="text-center">
                    <em class="h4 text-mute c-text-warning">No Schedule Added!</em><br>
                    <small class="text-muted">No Schedule added yet for collecting contributions for magazine.</small>
                </p>
            </div>
            <div class="item">
                <p class="text-center">
                    <em class="h4 text-mute c-text-info">Keep your eyes open!</em><br>
                    <small class="text-muted">A schedule will be announced soon.</small>
                </p>
            </div>
        </div>
        <a class="left carousel-control" href="#c-slide" data-slide="prev">
            <i class="fa fa-angle-left"></i>
        </a>
        <a class="right carousel-control" href="#c-slide" data-slide="next">
            <i class="fa fa-angle-right"></i>
        </a>
    </div>
</section>

magfetch/templates/landing/pages/snippets/chunks/contribution-list.html
{% load static %}

<!-- Datatable CSS -->
<link rel="stylesheet" href="{% static 'vendor/datatable/dataTables.min.css' %}" type="text/css" />

<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="text-center">
            <button id="download_btn" class="hide btn btn-md btn-dark">
                <span class="c-text-info">Download Files as Zip</span>
            </button>
        </div>
        <!-- Zip Download progress and Result -->
        <div class="progress hide" id="progress_bar">
            <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"
                style="width: 0%;">
            </div>
        </div>
        <p class="hide" id="result"></p>
        <input type="hidden" id="zip-name" name="zip-name" value="{{ request.user.profile.get_smallname }}">
        <!-- Zip Download progress and Result -->

        <div class="table-responsive">
            <table id="datatable" class="table table-bordered row-border b-t b-light" style="width:100%">
                <thead class="text-dark">
                    <tr>
                        <th class="text-center">
                            <span id="check-all">
                                <i class="fa fa-square" id="dflt"></i>
                                <i class="fa fa-check-square hide" id="chkd"></i>
                                <i class="fa fa-square hide" id="uchkd"></i>
                            </span>
                        </th>
                        <th>#</th>
                        <th class="text-center">Title</th>
                        <th class="text-center">Category</th>
                        <!-- <th class="text-center">
                            <span class="label bg-dark">File</span>
                        </th> -->
                        <th class="text-center">
                            Action
                        </th>
                        <th class="text-center">Uploaded at</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in contributions %}
                    <tr {% if object.is_selected == True %}class="bg-c-soft-green" {% endif %}>
                        <td class="text-center">
                            <div>
                                <!-- <input type="checkbox" class="check-box m-t-sm" data-url="http://magfetch.pythonanywhere.com{{object.file.url}}"> -->
                                <input type="checkbox" class="check-box m-t-sm"
                                    data-url="http://127.0.0.1:8000{{object.file.url}}">
                            </div>
                        </td>
                        <td>{{ forloop.counter }}</td>
                        <td>{{object.title}}</td>
                        <td>{{object.category}}</td>
                        <!-- <td class="text-center">
                            {% if object.category.category_for == 0 %}
                            <iframe class="doc" src="https://docs.google.com/gview?url=http://magfetch.pythonanywhere.com{{object.file.url}}&embedded=true"
                                width="270" height="60"></iframe>
                            <iframe class="doc" src="#" width="270" height="60"></iframe>
                            {% endif %}

                            {% if object.category.category_for == 1 %}
                            <a href="{{object.file.url}}" class="c-thumbnail" title="{{object.title}}">
                                <img src="{{object.file.url}}" alt="{{object.title}}" width="270" height="60">
                            </a>
                            {% endif %}
                        </td> -->
                        <td>
                            <button type="button" class="btn btn-sm btn-raised ripple-effect btn-info js-view-contribution"
                                value="{{object.slug}}" data-category="{{object.category.category_for}}" data-file="{{object.file.url}}" 
                                data-title="{{object.title}}" data-toggle="modal"
                                data-target="#modal-view-contribution">
                                View
                            </button>
                            <a class="btn btn-sm btn-raised ripple-effect btn-default" href="http://127.0.0.1:8000{{object.file.url}}" download>
                                <span class="c-text-dark">Download</span>
                            </a>
                            <button type="button" class="btn btn-sm btn-raised ripple-effect btn-danger js-delete-contribution"
                                value="{{object.slug}}" data-selected="{{object.is_selected}}" data-toggle="modal"
                                data-target="#modal-delete-contribution">
                                Delete
                            </button>
                            
                        </td>
                        <td width="7%">
                            {{object.created_at}}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% include 'landing/pages/snippets/chunks/modals/modals.html' %}

<script>
    $(".js-view-contribution").click(function() {
        var $this = $(this);
        var slug = $this.val();
        var file_url = $this.data("file");
        var category = $this.data("category");
        var title = $this.data("title");
        //var file_html = document.getElementById('file');

        if (category == 0){
            $('#file').html("<iframe class='doc' id='iframe' \
            src='https://docs.google.com/gview?url=http://magfetch.pythonanywhere.com"+file_url+"&embedded=true'\
                width='270' height='60'></iframe>");
        }
        else if (category == 1){
            $('#file').html(" <a href='"+file_url+"' class='c-thumbnail'> \
            <img src='"+file_url+"' alt='"+title+" class='img-fluid' height='480' width='640' /> \
            ");
        }
        else{
            $('#file').html("<h3>File not found!!!</h3>").css('color', '#B93232');
        };
        $('#viewContribution').html("<span>Contribution Title</span>: <span class='font-20 font-bold text-info'> \
            "+title+"</span> ");
        
        //console.log($this);
        //console.log(slug);
        //console.log(file_url);
        //console.log(category);
        //console.log(title);
    });
</script>

<script>
    $(".js-delete-contribution").click(function() {
        let contribution_slug = this.value ;
        $('#contribution_slug_modal2').val(contribution_slug);
        //console.log(contribution_slug);
    });
    document.querySelector('#form1').addEventListener('submit', function(e) {
        let form = this;
        e.preventDefault();
        form.submit();
        
    });
</script>

<!-- Datatable JS -->
<script src="{% static 'vendor/datatable/datatable-conf.js' %}"></script>
<script src="{% static 'vendor/datatable/dataTables.min.js' %}"></script>

<!-- Zip Downloader JS -->
<script src="{% static 'vendor/zip-downloader/jszip.min.js' %}"></script>
<script src="{% static 'vendor/zip-downloader/jszip-utils.js' %}"></script>
<script src="{% static 'vendor/zip-downloader/zip-config.js' %}"></script>
<script src="{% static 'vendor/zip-downloader/FileSaver.js' %}"></script>

magfetch/templates/landing/pages/snippets/chunks/contribution.html
<section class="panel b-primary text-center">
    <ul class="list-group">
        <li class="list-group-item">
            <small class="c-text-primary">Your Uploaded Contributions will be </small>
            <strong>used for</strong>
            <strong>University Magazine</strong>
        </li>
        <li class="list-group-item">
            <small class="c-text-primary">
                “A journey of a thousand miles must begin with a single step.”
            </small>-
            <i>Lao Tzu Tweet</i>
        </li>
    </ul>
    <footer class="panel-footer">
        <a href="{% url 'contribution:upload' %}" class="btn btn-primary m-t m-b btn-raised ripple-effect">
            Continue to Upload
        </a>
    </footer>
</section>

magfetch/templates/landing/pages/snippets/chunks/date-expired.html
<section class="panel panel-default">
    <div class="carousel slide auto panel-body" id="c-slide">
        <ol class="carousel-indicators out">
            <li data-target="#c-slide" data-slide-to="0" class="active"></li>
            <li data-target="#c-slide" data-slide-to="1" class=""></li>
        </ol>
        <div class="carousel-inner">
            <div class="item active">
                <p class="text-center">
                    <em class="h4 text-mute c-text-warning">Date Expired!</em><br>
                    <small class="text-danger">New Contribution Submitting Schedule has been Expired</small>
                </p>
            </div>
        </div>
        <a class="left carousel-control" href="#c-slide" data-slide="prev">
            <i class="fa fa-angle-left"></i>
        </a>
        <a class="right carousel-control" href="#c-slide" data-slide="next">
            <i class="fa fa-angle-right"></i>
        </a>
    </div>
</section>

magfetch/templates/landing/pages/snippets/chunks/image.html
<section class="panel b-primary text-center">
    <ul class="list-group">
        <li class="list-group-item">
            <small class="c-text-primary">Image Format Supported</small>:
            <strong>.jpg</strong>,
            <strong>.jpeg</strong>,
            <strong>.png</strong>,
            <strong>.svg</strong>
        </li>
        <li class="list-group-item">
            <small class="c-text-primary">Maximum Image Size</small>:
            <strong>2.5MB</strong>
        </li>
    </ul>
    <footer class="panel-footer">
        <a href="{% url 'contribution:image_upload' %}" class="btn btn-primary m-t m-b">
            Upload Image
        </a>
    </footer>
</section>